### ISSUE TITLE
Add travis 🐧

### ISSUE THREAD

**Issue by jimfilippou** [jimfilippou/ire#3]
I have to add this Travis file

```yaml

language: go

go:
  - 1.13.5

services:
  - elasticsearch

script:
  - go test
```
